"""retira imagen user

Revision ID: 0dbaeb8182ec
Revises: 279c125e79d2
Create Date: 2022-10-24 16:39:09.916718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbaeb8182ec'
down_revision = '279c125e79d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('img', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
