"""modifica texto y portada

Revision ID: 1ae2b2da2dd7
Revises: 8745afe8f8df
Create Date: 2022-10-18 23:36:41.764677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae2b2da2dd7'
down_revision = '8745afe8f8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos', 'fecha_evento',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('eventos', 'texto_portada',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('eventos', 'img_portada',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('regalos', 'img_regalo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('usuarios', 'img',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'img',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)
    op.alter_column('regalos', 'img_regalo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('eventos', 'img_portada',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('eventos', 'texto_portada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('eventos', 'fecha_evento',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
