"""imagenes gifts y users

Revision ID: 279c125e79d2
Revises: 1ae2b2da2dd7
Create Date: 2022-10-19 11:24:46.820999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279c125e79d2'
down_revision = '1ae2b2da2dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dedicatorias', 'nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('dedicatorias', 'contenido',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('regalos', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('regalos', 'descripcion',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('regalos', 'img_regalo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('regalos', 'precio',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('usuarios', 'img',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'img',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('regalos', 'precio',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('regalos', 'img_regalo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('regalos', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('regalos', 'nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('dedicatorias', 'contenido',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('dedicatorias', 'nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
