"""primera migracion

Revision ID: 8745afe8f8df
Revises: 
Create Date: 2022-10-17 19:28:22.554241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8745afe8f8df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=True),
    sa.Column('apellidos', sa.String(length=160), nullable=True),
    sa.Column('dni', sa.String(length=8), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('img', sa.String(length=160), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banco', sa.String(length=60), nullable=True),
    sa.Column('nro_cuenta', sa.String(length=50), nullable=True),
    sa.Column('titular', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_evento', sa.String(length=200), nullable=True),
    sa.Column('fecha_evento', sa.Date(), nullable=True),
    sa.Column('texto_portada', sa.String(length=300), nullable=True),
    sa.Column('img_portada', sa.String(length=50), nullable=True),
    sa.Column('configuraciones', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dedicatorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('contenido', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regalos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('img_regalo', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.String(length=12), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regalos')
    op.drop_table('dedicatorias')
    op.drop_table('eventos')
    op.drop_table('cuentas')
    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
